### ISSUE TITLE
Long Method: changeState

### ISSUE THREAD

**Issue by UtkarshKr007** [umm-csci-software-quality-f20/machine-shop-refactoring-simulationx#3]
The if and else statements do various tasks and take quite a few lines. They could be replaced by method calls reducing the size of the method itself.

**Comment by deglm006** [comment]
I would suggest adding #2 as a dependency for this issue. I feel like it would be hard to work on both this issue and #2 at the same time and work on #2 seems like in would help with this issue, but I see no benefit of doing it in the other order.
